version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: .clound/nginx.dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
      - php
  mysql: 
    image: mariadb:10.5
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./.clound/mysql:/var/lib/mysql
  php:
    build:
      context: .
      dockerfile: .clound/php.dockerfile
    volumes:
      - ./src:/var/www/html