version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: .clound/nginx.prod.dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mysql
      - php
  php:
    build:
      context: .
      dockerfile: .clound/php.prod.dockerfile