version: '3.8'

services:
  nginx:
    build:
      context: .cloud/
      dockerfile: nginx.prod.dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mysql
      - php
  php:
    build:
      context: .cloud/
      dockerfile: php.prod.dockerfile
  assets:
    image: node:current-alpine
    volumes:
      - ./src:/var/www/hrml
    command: ["/bin/sh", "-c", "npm install && npm run production"]
    working_dir: /var/www/html